Name: 05-03-2023

Songs:
  CuesPath: Dropbox/cues/
  TracksPath: /Users/brentthayer/Dropbox/TRACKS/TRACKS/
  1: great_things.yaml
  2: graves_into_gardens.yaml

Returns:
  1: Click
  2: Bass
  3: Loops
  4: Guitars
  5: FX
